module.exports = {
	afriso: {
		apr234nf: "require('../devices/afriso/apr234nf/device.json')",
		co2sensor: "require('../devices/afriso/co2sensor/device.json')",
		dta_20_e: "require('../devices/afriso/dta_20_e/device.json')",
		room_temperature_and_humidity_sensor_ftf:
			"require('../devices/afriso/room_temperature_and_humidity_sensor_ftf/device.json')",
		room_temperature_sensor_ft: "require('../devices/afriso/room_temperature_sensor_ft/device.json')",
		temperature_and_humidity_sensor_ftm_tf:
			"require('../devices/afriso/temperature_and_humidity_sensor_ftm_tf/device.json')",
		temperature_sensor_ftm_t: "require('../devices/afriso/temperature_sensor_ftm_t/device.json')",
		wireless_smoke_alarm_asd_10: "require('../devices/afriso/wireless_smoke_alarm_asd_10/device.json')",
		wireless_smoke_alarm_asd_20: "require('../devices/afriso/wireless_smoke_alarm_asd_20/device.json')",
	},
	dimplex: {
		dl_50_we2: "require('../devices/dimplex/dl_50_we2/device.json')",
	},
	easyfit: {
		ethsx: "require('../devices/easyfit/ethsx/device.json')",
	},
	eimsig_efp_gmbh: {
		emfsge00_eep_a5140a: "require('../devices/eimsig_efp_gmbh/emfsge00_eep_a5140a/device.json')",
		emuse00_eep_a51401: "require('../devices/eimsig_efp_gmbh/emuse00_eep_a51401/device.json')",
		emuse00_eep_a51407: "require('../devices/eimsig_efp_gmbh/emuse00_eep_a51407/device.json')",
		emuse00_eep_a51409: "require('../devices/eimsig_efp_gmbh/emuse00_eep_a51409/device.json')",
	},
	eltako: {
		dsz14: "require('../devices/eltako/dsz14/device.json')",
		etronic: "require('../devices/eltako/etronic/device.json')",
		f3z14d_electricity: "require('../devices/eltako/f3z14d_electricity/device.json')",
		f3z14d_gas: "require('../devices/eltako/f3z14d_gas/device.json')",
		f3z14d_water: "require('../devices/eltako/f3z14d_water/device.json')",
		f4hk14: "require('../devices/eltako/f4hk14/device.json')",
		f4pt: "require('../devices/eltako/f4pt/device.json')",
		f4pt55: "require('../devices/eltako/f4pt55/device.json')",
		f4sr14led: "require('../devices/eltako/f4sr14led/device.json')",
		fabh65s: "require('../devices/eltako/fabh65s/device.json')",
		fae14lpr: "require('../devices/eltako/fae14lpr/device.json')",
		fae14ssr: "require('../devices/eltako/fae14ssr/device.json')",
		faft60: "require('../devices/eltako/faft60/device.json')",
		fah: "require('../devices/eltako/fah/device.json')",
		fah60b: "require('../devices/eltako/fah60b/device.json')",
		fah65s: "require('../devices/eltako/fah65s/device.json')",
		fbh65: "require('../devices/eltako/fbh65/device.json')",
		fbh65s: "require('../devices/eltako/fbh65s/device.json')",
		fd62np230v: "require('../devices/eltako/fd62np230v/device.json')",
		fd62npn230v: "require('../devices/eltako/fd62npn230v/device.json')",
		fdg14: "require('../devices/eltako/fdg14/device.json')",
		fdg71l: "require('../devices/eltako/fdg71l/device.json')",
		ffg7b_a51409: "require('../devices/eltako/ffg7b_a51409/device.json')",
		ffg7b_f61000: "require('../devices/eltako/ffg7b_f61000/device.json')",
		ffkb: "require('../devices/eltako/ffkb/device.json')",
		ffr61230v: "require('../devices/eltako/ffr61230v/device.json')",
		fft55b_a50402: "require('../devices/eltako/fft55b_a50402/device.json')",
		fft60sb_a50402: "require('../devices/eltako/fft60sb_a50402/device.json')",
		fft65b_a50402: "require('../devices/eltako/fft65b_a50402/device.json')",
		ffte: "require('../devices/eltako/ffte/device.json')",
		fftf65b_a50402: "require('../devices/eltako/fftf65b_a50402/device.json')",
		fhb: "require('../devices/eltako/fhb/device.json')",
		fhd60sb: "require('../devices/eltako/fhd60sb/device.json')",
		fhf: "require('../devices/eltako/fhf/device.json')",
		fhk14: "require('../devices/eltako/fhk14/device.json')",
		fih65s: "require('../devices/eltako/fih65s/device.json')",
		fj621236v_dc: "require('../devices/eltako/fj621236v_dc/device.json')",
		fj62np230v: "require('../devices/eltako/fj62np230v/device.json')",
		fkdam: "require('../devices/eltako/fkdam/device.json')",
		fkf65: "require('../devices/eltako/fkf65/device.json')",
		fkld61: "require('../devices/eltako/fkld61/device.json')",
		fkssv: "require('../devices/eltako/fkssv/device.json')",
		fl62230v: "require('../devices/eltako/fl62230v/device.json')",
		fl62np230v: "require('../devices/eltako/fl62np230v/device.json')",
		fld61: "require('../devices/eltako/fld61/device.json')",
		flgtf55_temperature_and_humidity: "require('../devices/eltako/flgtf55_temperature_and_humidity/device.json')",
		flgtf55_tvoc: "require('../devices/eltako/flgtf55_tvoc/device.json')",
		fmh4: "require('../devices/eltako/fmh4/device.json')",
		fmms44sb: "require('../devices/eltako/fmms44sb/device.json')",
		fms14_3219: "require('../devices/eltako/fms14_3219/device.json')",
		fms61np230v_2_channel_mode: "require('../devices/eltako/fms61np230v_2_channel_mode/device.json')",
		fms65esb: "require('../devices/eltako/fms65esb/device.json')",
		fmz61230v: "require('../devices/eltako/fmz61230v/device.json')",
		fr62230v: "require('../devices/eltako/fr62230v/device.json')",
		fr62np230v: "require('../devices/eltako/fr62np230v/device.json')",
		frgbw14_iobroker_controls_master: "require('../devices/eltako/frgbw14_iobroker_controls_master/device.json')",
		frgbw14_iobroker_is_master: "require('../devices/eltako/frgbw14_iobroker_is_master/device.json')",
		frgbw14_single_or_all_channel: "require('../devices/eltako/frgbw14_single_or_all_channel/device.json')",
		frgbw71l_iobroker_controls_master: "require('../devices/eltako/frgbw71l_iobroker_controls_master/device.json')",
		frgbw71l_iobroker_is_master: "require('../devices/eltako/frgbw71l_iobroker_is_master/device.json')",
		frgbw71l_single_or_all_channel: "require('../devices/eltako/frgbw71l_single_or_all_channel/device.json')",
		frw: "require('../devices/eltako/frw/device.json')",
		frwb: "require('../devices/eltako/frwb/device.json')",
		fsb14: "require('../devices/eltako/fsb14/device.json')",
		fsb61np230v: "require('../devices/eltako/fsb61np230v/device.json')",
		fsb71230v: "require('../devices/eltako/fsb71230v/device.json')",
		fsb7124v: "require('../devices/eltako/fsb7124v/device.json')",
		fsb712x230v: "require('../devices/eltako/fsb712x230v/device.json')",
		fsg14110v: "require('../devices/eltako/fsg14110v/device.json')",
		fsg71110v: "require('../devices/eltako/fsg71110v/device.json')",
		fsr142x: "require('../devices/eltako/fsr142x/device.json')",
		fsr144x: "require('../devices/eltako/fsr144x/device.json')",
		fsr14ssr: "require('../devices/eltako/fsr14ssr/device.json')",
		fsr61230V_1114: "require('../devices/eltako/fsr61230V_1114/device.json')",
		fsr61230v_1014: "require('../devices/eltako/fsr61230v_1014/device.json')",
		fsr61824v_uc: "require('../devices/eltako/fsr61824v_uc/device.json')",
		fsr61np230v: "require('../devices/eltako/fsr61np230v/device.json')",
		fsr61va_control: "require('../devices/eltako/fsr61va_control/device.json')",
		fsr61va_measurement: "require('../devices/eltako/fsr61va_measurement/device.json')",
		fsr70s230v: "require('../devices/eltako/fsr70s230v/device.json')",
		fsr712x230v: "require('../devices/eltako/fsr712x230v/device.json')",
		fsr71np230v: "require('../devices/eltako/fsr71np230v/device.json')",
		fsr71np2x230v: "require('../devices/eltako/fsr71np2x230v/device.json')",
		fsr71np4x230v: "require('../devices/eltako/fsr71np4x230v/device.json')",
		fss1212vdc: "require('../devices/eltako/fss1212vdc/device.json')",
		fssa230v: "require('../devices/eltako/fssa230v/device.json')",
		fssg230v: "require('../devices/eltako/fssg230v/device.json')",
		fsud230v: "require('../devices/eltako/fsud230v/device.json')",
		fsva230v_control: "require('../devices/eltako/fsva230v_control/device.json')",
		fsva230v_measurement: "require('../devices/eltako/fsva230v_measurement/device.json')",
		ft55: "require('../devices/eltako/ft55/device.json')",
		fta55d: "require('../devices/eltako/fta55d/device.json')",
		fta55j: "require('../devices/eltako/fta55j/device.json')",
		fta55l: "require('../devices/eltako/fta55l/device.json')",
		fta65d: "require('../devices/eltako/fta65d/device.json')",
		fta65j: "require('../devices/eltako/fta65j/device.json')",
		fta65l: "require('../devices/eltako/fta65l/device.json')",
		ftaf55d230v: "require('../devices/eltako/ftaf55d230v/device.json')",
		ftfb_a50402: "require('../devices/eltako/ftfb_a50402/device.json')",
		ftfsb_a50402: "require('../devices/eltako/ftfsb_a50402/device.json')",
		ftk: "require('../devices/eltako/ftk/device.json')",
		ftkbgr: "require('../devices/eltako/ftkbgr/device.json')",
		ftkbrw: "require('../devices/eltako/ftkbrw/device.json')",
		ftke: "require('../devices/eltako/ftke/device.json')",
		ftr55dsb_fhk: "require('../devices/eltako/ftr55dsb_fhk/device.json')",
		ftr55dsb_tf61: "require('../devices/eltako/ftr55dsb_tf61/device.json')",
		ftr55hb_fhk: "require('../devices/eltako/ftr55hb_fhk/device.json')",
		ftr55hb_tf61: "require('../devices/eltako/ftr55hb_tf61/device.json')",
		ftr55sb_fhk: "require('../devices/eltako/ftr55sb_fhk/device.json')",
		ftr55sb_tf61: "require('../devices/eltako/ftr55sb_tf61/device.json')",
		ftr65dsb_fhk: "require('../devices/eltako/ftr65dsb_fhk/device.json')",
		ftr65dsb_tf61: "require('../devices/eltako/ftr65dsb_tf61/device.json')",
		ftr65hb_fhk: "require('../devices/eltako/ftr65hb_fhk/device.json')",
		ftr65hb_tf61: "require('../devices/eltako/ftr65hb_tf61/device.json')",
		ftr65sb_fhk: "require('../devices/eltako/ftr65sb_fhk/device.json')",
		ftr65sb_tf61: "require('../devices/eltako/ftr65sb_tf61/device.json')",
		ftrf65hb_fhk: "require('../devices/eltako/ftrf65hb_fhk/device.json')",
		ftrf65sb_fhk: "require('../devices/eltako/ftrf65sb_fhk/device.json')",
		ftrf65sb_tf61: "require('../devices/eltako/ftrf65sb_tf61/device.json')",
		fts14em: "require('../devices/eltako/fts14em/device.json')",
		fud14: "require('../devices/eltako/fud14/device.json')",
		fud14800w: "require('../devices/eltako/fud14800w/device.json')",
		fud61np230v__1019: "require('../devices/eltako/fud61np230v__1019/device.json')",
		fud61npn230v__1019: "require('../devices/eltako/fud61npn230v__1019/device.json')",
		fud71: "require('../devices/eltako/fud71/device.json')",
		fwg14ms: "require('../devices/eltako/fwg14ms/device.json')",
		fws61: "require('../devices/eltako/fws61/device.json')",
		fws81: "require('../devices/eltako/fws81/device.json')",
		fwz12: "require('../devices/eltako/fwz12/device.json')",
		fwz14: "require('../devices/eltako/fwz14/device.json')",
		tf100a: "require('../devices/eltako/tf100a/device.json')",
		tf100d: "require('../devices/eltako/tf100d/device.json')",
		tf100l: "require('../devices/eltako/tf100l/device.json')",
		tf100ssr: "require('../devices/eltako/tf100ssr/device.json')",
		tf1ft: "require('../devices/eltako/tf1ft/device.json')",
		tf2ft: "require('../devices/eltako/tf2ft/device.json')",
		tf2ft55: "require('../devices/eltako/tf2ft55/device.json')",
		tf2zt: "require('../devices/eltako/tf2zt/device.json')",
		tf2zt55: "require('../devices/eltako/tf2zt55/device.json')",
		tf4ft: "require('../devices/eltako/tf4ft/device.json')",
		tf4ft55: "require('../devices/eltako/tf4ft55/device.json')",
		tf61d230v: "require('../devices/eltako/tf61d230v/device.json')",
		tf61j230v: "require('../devices/eltako/tf61j230v/device.json')",
		tf61l230v: "require('../devices/eltako/tf61l230v/device.json')",
		tf61r230v: "require('../devices/eltako/tf61r230v/device.json')",
		tf8fm: "require('../devices/eltako/tf8fm/device.json')",
		tfrwb: "require('../devices/eltako/tfrwb/device.json')",
		tfta55d: "require('../devices/eltako/tfta55d/device.json')",
		tfta55dl: "require('../devices/eltako/tfta55dl/device.json')",
		tfta55j: "require('../devices/eltako/tfta55j/device.json')",
		tfta55l: "require('../devices/eltako/tfta55l/device.json')",
		tfta65d: "require('../devices/eltako/tfta65d/device.json')",
		tfta65j: "require('../devices/eltako/tfta65j/device.json')",
		tfta65l: "require('../devices/eltako/tfta65l/device.json')",
		tfttb: "require('../devices/eltako/tfttb/device.json')",
	},
	enocean_gmbh: {
		eoscaweo: "require('../devices/enocean_gmbh/eoscaweo/device.json')",
		eoswaweo: "require('../devices/enocean_gmbh/eoswaweo/device.json')",
		ptm200: "require('../devices/enocean_gmbh/ptm200/device.json')",
		ptm210: "require('../devices/enocean_gmbh/ptm210/device.json')",
		ptm215: "require('../devices/enocean_gmbh/ptm215/device.json')",
		stm_250: "require('../devices/enocean_gmbh/stm_250/device.json')",
		stm_350: "require('../devices/enocean_gmbh/stm_350/device.json')",
	},
	eurotronic: {
		stella_e: "require('../devices/eurotronic/stella_e/device.json')",
	},
	hoppe: {
		ehandle_connecthome: "require('../devices/hoppe/ehandle_connecthome/device.json')",
		secusignal: "require('../devices/hoppe/secusignal/device.json')",
	},
	hora: {
		smartdrive_mx: "require('../devices/hora/smartdrive_mx/device.json')",
	},
	kessel: {
		staufix_control: "require('../devices/kessel/staufix_control/device.json')",
	},
	kieback_and_peter: {
		md15ftlhe: "require('../devices/kieback_and_peter/md15ftlhe/device.json')",
		md15ftlov: "require('../devices/kieback_and_peter/md15ftlov/device.json')",
		rbw322ftl: "require('../devices/kieback_and_peter/rbw322ftl/device.json')",
	},
	maco: {
		etronic: "require('../devices/maco/etronic/device.json')",
	},
	micropelt: {
		mva002: "require('../devices/micropelt/mva002/device.json')",
		mva003: "require('../devices/micropelt/mva003/device.json')",
		mva004: "require('../devices/micropelt/mva004/device.json')",
		mva005: "require('../devices/micropelt/mva005/device.json')",
		mva009: "require('../devices/micropelt/mva009/device.json')",
	},
	nodon: {
		card_switch_ccs2101: "require('../devices/nodon/card_switch_ccs2101/device.json')",
		door_and_window_sensor_sdo2105: "require('../devices/nodon/door_and_window_sensor_sdo2105/device.json')",
		floor_switch: "require('../devices/nodon/floor_switch/device.json')",
		micro_smart_plug_msp2111: "require('../devices/nodon/micro_smart_plug_msp2111/device.json')",
		motion_sensor_pir2101_: "require('../devices/nodon/motion_sensor_pir2101_/device.json')",
		onoff_lighting_relay_switch_sin2201:
			"require('../devices/nodon/onoff_lighting_relay_switch_sin2201/device.json')",
		rollershutter_sin2rs01: "require('../devices/nodon/rollershutter_sin2rs01/device.json')",
		soft_button_tsb2201: "require('../devices/nodon/soft_button_tsb2201/device.json')",
		soft_remote: "require('../devices/nodon/soft_remote/device.json')",
		temperature_and_humidity_sensor_stph2105:
			"require('../devices/nodon/temperature_and_humidity_sensor_stph2105/device.json')",
		temperature_sensor_stp2105: "require('../devices/nodon/temperature_sensor_stp2105/device.json')",
		wall_switch: "require('../devices/nodon/wall_switch/device.json')",
	},
	omnio: {
		wsch102: "require('../devices/omnio/wsch102/device.json')",
	},
	opus: {
		gnbh63appw: "require('../devices/opus/gnbh63appw/device.json')",
	},
	oventrop: {
		mote_420: "require('../devices/oventrop/mote_420/device.json')",
		rcon_t2p: "require('../devices/oventrop/rcon_t2p/device.json')",
		rtronic_rt_b_a51002: "require('../devices/oventrop/rtronic_rt_b_a51002/device.json')",
		rtronic_rt_b_a51006__rps: "require('../devices/oventrop/rtronic_rt_b_a51006__rps/device.json')",
	},
	peha: {
		'451_fuebi_pf_ot': "require('../devices/peha/451_fuebi_pf_ot/device.json')",
		'452_fuebim_jr_ot': "require('../devices/peha/452_fuebim_jr_ot/device.json')",
		d_450_fu_fk: "require('../devices/peha/d_450_fu_fk/device.json')",
		d_4511_fuebim_st: "require('../devices/peha/d_4511_fuebim_st/device.json')",
		d_451_fubm: "require('../devices/peha/d_451_fubm/device.json')",
		easyclick_sender: "require('../devices/peha/easyclick_sender/device.json')",
	},
	pentair: {
		transmitter_ftjp: "require('../devices/pentair/transmitter_ftjp/device.json')",
	},
	permundo: {
		psc_152: "require('../devices/permundo/psc_152/device.json')",
		psc_234: "require('../devices/permundo/psc_234/device.json')",
	},
	rehau: {
		smart_guard: "require('../devices/rehau/smart_guard/device.json')",
		smart_guard_inline__ontop: "require('../devices/rehau/smart_guard_inline__ontop/device.json')",
	},
	schueco: {
		sensetrack_wireless: "require('../devices/schueco/sensetrack_wireless/device.json')",
	},
	siegenia: {
		senso_secure: "require('../devices/siegenia/senso_secure/device.json')",
	},
	soda: {
		s8: "require('../devices/soda/s8/device.json')",
	},
	telefunken: {
		motion_detector_bm1: "require('../devices/telefunken/motion_detector_bm1/device.json')",
		plug_actuator_ses_fseo: "require('../devices/telefunken/plug_actuator_ses_fseo/device.json')",
	},
	thermokon: {
		sab: "require('../devices/thermokon/sab/device.json')",
		sab05: "require('../devices/thermokon/sab05/device.json')",
		sr04: "require('../devices/thermokon/sr04/device.json')",
		sr04_p: "require('../devices/thermokon/sr04_p/device.json')",
		sr04_p_rh: "require('../devices/thermokon/sr04_p_rh/device.json')",
		sr04_pms: "require('../devices/thermokon/sr04_pms/device.json')",
		sr04_pms_rh: "require('../devices/thermokon/sr04_pms_rh/device.json')",
		sr04_ps_fs5: "require('../devices/thermokon/sr04_ps_fs5/device.json')",
		sr04_pst_fs5: "require('../devices/thermokon/sr04_pst_fs5/device.json')",
		sr04_pt: "require('../devices/thermokon/sr04_pt/device.json')",
		sr04_pt_rh: "require('../devices/thermokon/sr04_pt_rh/device.json')",
		sr04_rh: "require('../devices/thermokon/sr04_rh/device.json')",
		sr04_s_fs5: "require('../devices/thermokon/sr04_s_fs5/device.json')",
		sr04_t: "require('../devices/thermokon/sr04_t/device.json')",
		sr07_ms: "require('../devices/thermokon/sr07_ms/device.json')",
		sr07_ms_rh: "require('../devices/thermokon/sr07_ms_rh/device.json')",
		sr07_p: "require('../devices/thermokon/sr07_p/device.json')",
		sr07_p_rh: "require('../devices/thermokon/sr07_p_rh/device.json')",
		sr07_pms: "require('../devices/thermokon/sr07_pms/device.json')",
		sr07_pms_rh: "require('../devices/thermokon/sr07_pms_rh/device.json')",
		sr07_pt: "require('../devices/thermokon/sr07_pt/device.json')",
		sr07_pt_rh: "require('../devices/thermokon/sr07_pt_rh/device.json')",
		sr07_t: "require('../devices/thermokon/sr07_t/device.json')",
		sr07_t_rh: "require('../devices/thermokon/sr07_t_rh/device.json')",
		sr65_a50214: "require('../devices/thermokon/sr65_a50214/device.json')",
		srmds_solar_a50602: "require('../devices/thermokon/srmds_solar_a50602/device.json')",
		srmds_solar_a50701: "require('../devices/thermokon/srmds_solar_a50701/device.json')",
		srmds_solar_a50702: "require('../devices/thermokon/srmds_solar_a50702/device.json')",
		srmds_solar_a50703: "require('../devices/thermokon/srmds_solar_a50703/device.json')",
		srmds_solar_a50802: "require('../devices/thermokon/srmds_solar_a50802/device.json')",
		srmds_solar_default_a50801: "require('../devices/thermokon/srmds_solar_default_a50801/device.json')",
		srmds_solar_f60202: "require('../devices/thermokon/srmds_solar_f60202/device.json')",
	},
	trio2sys: {
		outdoor_3050c_temperature_sensor: "require('../devices/trio2sys/outdoor_3050c_temperature_sensor/device.json')",
	},
	viessmann: {
		raumthermostat_7554508501032100: "require('../devices/viessmann/raumthermostat_7554508501032100/device.json')",
		temperature_and_humidity_sensor_7554951:
			"require('../devices/viessmann/temperature_and_humidity_sensor_7554951/device.json')",
		temperature_sensor_7554507: "require('../devices/viessmann/temperature_sensor_7554507/device.json')",
	},
	winkhaus: {
		fmvsw_eep_a51401: "require('../devices/winkhaus/fmvsw_eep_a51401/device.json')",
		fmvsw_eep_a5140a: "require('../devices/winkhaus/fmvsw_eep_a5140a/device.json')",
		fmvsw_eep_d50001: "require('../devices/winkhaus/fmvsw_eep_d50001/device.json')",
	},
	x_virtual: {
		room_operating_panel_a51006: "require('../devices/x_virtual/room_operating_panel_a51006/device.json')",
		switch: "require('../devices/x_virtual/switch/device.json')",
		windowdoor_contact: "require('../devices/x_virtual/windowdoor_contact/device.json')",
	},
};
