/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'Remove': {
		'en': 'Remove',
		'de': 'Entfernen',
		'ru': 'Удалить',
		'pt': 'Retirar',
		'nl': 'Verwijderen',
		'fr': 'Retirer',
		'it': 'Rimuovere',
		'es': 'Eliminar',
		'pl': 'Usunąć',
		'zh-cn': '去掉'
	},
	'enocean adapter settings': {
		'en': 'Adapter settings for enocean',
		'de': 'Adaptereinstellungen für enocean',
		'ru': 'Настройки адаптера для enocean',
		'pt': 'Configurações do adaptador para enocean',
		'nl': 'Adapterinstellingen voor enocean',
		'fr': 'Paramètres d\'adaptateur pour enocean',
		'it': 'Impostazioni dell\'adattatore per enocean',
		'es': 'Ajustes del adaptador para enocean',
		'pl': 'Ustawienia adaptera dla enocean',
		'zh-cn': 'enocean的适配器设置'
	},
	'Save': {
		'en': 'Save',
		'de': 'speichern',
		'ru': 'Сохранить',
		'pt': 'Salve ',
		'nl': 'Sparen',
		'fr': 'sauvegarder',
		'it': 'Salva',
		'es': 'Salvar',
		'pl': 'Zapisać',
		'zh-cn': '保存'
	},
	'Devices': {
		'en': 'devices',
		'de': 'Geräte',
		'ru': 'устройства',
		'pt': 'dispositivos',
		'nl': 'apparaten',
		'fr': 'dispositifs',
		'it': 'dispositivi',
		'es': 'dispositivos',
		'pl': 'urządzenia',
		'zh-cn': '设备'
	},
	'Add new device': {
		'en': 'Add new device',
		'de': 'Neues Gerät hinzufügen',
		'ru': 'Добавить новое устройство',
		'pt': 'Adicionar novo dispositivo',
		'nl': 'Voeg een nieuw apparaat toe',
		'fr': 'Ajouter un nouvel appareil',
		'it': 'Aggiungi nuovo dispositivo',
		'es': 'Agrega un nuevo dispositivo',
		'pl': 'Dodaj nowe urządzenie',
		'zh-cn': '添加新设备'
	},
	'Autodetect': {
		'en': 'Autodetect',
		'de': 'Automatische Erkennung',
		'ru': 'Автоматическое распознавание',
		'pt': 'Detecção automática',
		'nl': 'Automatische detectie',
		'fr': 'Détection automatique',
		'it': 'Trovato automaticamente',
		'es': 'Detección automática',
		'pl': 'Automatyczne wykrywanie',
		'zh-cn': '自动侦测'
	},
	'Settings': {
		'en': 'Settings',
		'de': 'Einstellungen',
		'ru': 'Настройки',
		'pt': 'Configurações',
		'nl': 'Instellingen',
		'fr': 'Réglages',
		'it': 'impostazioni',
		'es': 'Configuraciones',
		'pl': 'Ustawienia',
		'zh-cn': '设定值'
	},
	'manufacturer': {
		'en': 'Manufacturer',
		'de': 'Hersteller',
		'ru': 'производитель',
		'pt': 'fabricante',
		'nl': 'fabrikant',
		'fr': 'fabricant',
		'it': 'produttore',
		'es': 'fabricante',
		'pl': 'producent',
		'zh-cn': '制造商'
	},
	'device': {
		'en': 'device',
		'de': 'Gerät',
		'ru': 'устройство',
		'pt': 'dispositivo',
		'nl': 'apparaat',
		'fr': 'dispositif',
		'it': 'dispositivo',
		'es': 'dispositivo',
		'pl': 'urządzenie',
		'zh-cn': '设备'
	},
	'Choose': {
		'en': 'Choose',
		'de': 'Wählen',
		'ru': 'выберите',
		'pt': 'Escolher',
		'nl': 'Kiezen',
		'fr': 'Choisir',
		'it': 'Scegliere',
		'es': 'Escoger',
		'pl': 'Wybierać',
		'zh-cn': '选择'
	},
	'Serial port': {
		'en': 'Serial port',
		'de': 'Serielle Schnittstelle',
		'ru': 'Серийный порт',
		'pt': 'Porta serial',
		'nl': 'Seriële poort',
		'fr': 'Port série',
		'it': 'Porta seriale',
		'es': 'Puerto serial',
		'pl': 'Port szeregowy',
		'zh-cn': '串行端口'
	},
	'Add device': {
		'en': 'Add device',
		'de': 'Gerät hinzufügen',
		'ru': 'Добавить устройство',
		'pt': 'Adicionar Dispositivo',
		'nl': 'Voeg toestel toe',
		'fr': 'Ajouter un appareil',
		'it': 'Aggiungi dispositivo',
		'es': 'Añadir dispositivo',
		'pl': 'Dodaj urządzenie',
		'zh-cn': '添加设备'
	},
	'Close': {
		'en': 'Close',
		'de': 'Schließen',
		'ru': 'Закрыть',
		'pt': 'Perto',
		'nl': 'Dichtbij',
		'fr': 'proche',
		'it': 'Vicino',
		'es': 'Cerca',
		'pl': 'Blisko',
		'zh-cn': '关'
	},
	'Autodetect device': {
		'en': 'Autodetect device',
		'de': 'Automatische Geräteerkennung',
		'ru': 'Автоопределение устройства',
		'pt': 'Dispositivo de detecção automática',
		'nl': 'Apparaat automatisch detecteren',
		'fr': "Détection automatique de l'appareil",
		'it': 'Rilevamento automatico del dispositivo',
		'es': 'Dispositivo de detección automática',
		'pl': 'Automatyczne wykrywanie urządzenia',
		'zh-cn': '自动检测装置'
	},
	'Note modal': {
		'en': 'Note: Only a small number of devices could be automaticly detected. If your device was not detected look into the log for more information.',
		'de': 'Hinweis: Nur eine kleine Anzahl von Geräten kann automatisch erkannt werden. Wenn Ihr Gerät nicht erkannt wurde, schauen sie im Log nach weiteren Informationen.',
		'ru': 'Примечание. Автоматически обнаруживается лишь небольшое количество устройств. Если ваше устройство не было обнаружено, загляните в журнал для получения дополнительной информации.',
		'pt': 'Nota: Apenas um pequeno número de dispositivos pode ser detectado automaticamente. Se o seu dispositivo não foi detectado, verifique o registro para obter mais informações.',
		'nl': 'Opmerking: slechts een klein aantal apparaten kan automatisch worden gedetecteerd. Als uw apparaat niet werd gedetecteerd, kijk dan in het logboek voor meer informatie.',
		'fr': "Remarque: Seul un petit nombre d'appareils peut être détecté automatiquement. Si votre appareil n'a pas été détecté, consultez le journal pour plus d'informations.",
		'it': 'Nota: è stato possibile rilevare automaticamente solo un numero limitato di dispositivi. Se il tuo dispositivo non è stato rilevato, guarda nel registro per ulteriori informazioni.',
		'es': 'Nota: Solo se pudo detectar automáticamente una pequeña cantidad de dispositivos. Si no se detectó su dispositivo, consulte el registro para obtener más información.',
		'pl': 'Uwaga: tylko niewielka liczba urządzeń mogła zostać wykryta automatycznie. Jeśli urządzenie nie zostało wykryte, zajrzyj do dziennika, aby uzyskać więcej informacji.',
		'zh-cn': '注意：只能自动检测少量设备。如果未检测到设备，请查看日志以获取更多信息。'
	},
	'Teachin button': {
		'en': 'Please follow the instruction of your device for Teach-in procedure.',
		'de': 'Befolgen Sie die Anweisungen Ihres Geräts zum Einlernen.',
		'ru': 'Пожалуйста, следуйте инструкциям вашего устройства для процедуры обучения.',
		'pt': 'Siga as instruções do seu dispositivo para o procedimento de aprendizagem.',
		'nl': 'Volg de instructies van uw apparaat voor de inleerprocedure.',
		'fr': "Veuillez suivre les instructions de votre appareil pour la procédure d'apprentissage.",
		'it': 'Seguire le istruzioni del dispositivo per la procedura di apprendimento.',
		'es': 'Siga las instrucciones de su dispositivo para el procedimiento de aprendizaje.',
		'pl': 'Postępuj zgodnie z instrukcją urządzenia dotyczącą procedury uczenia.',
		'zh-cn': '请按照设备的说明进行自学程序。'
	}
};
